name: n_bi
description: "N比"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.08"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  # below is 3rd dependency
  provider: ^6.0.5
  dartz: ^0.10.1
  kt_dart: ^1.1.0
  rxdart: ^0.27.7
  path_provider: ^2.1.5
  file_picker: ^5.3.2
  #获取pubspec.yaml中的配置信息
  package_info_plus: ^8.1.2
  home_widget: ^0.6.0
  #network
  dio: ^5.7.0
  # logger
  pretty_dio_logger: ^1.4.0
  dio_log: ^5.3.0
  #
  json_annotation: ^4.9.0
  # 生成.g文件
  freezed_annotation: ^2.4.4
  #route
  flutter_modular: ^6.3.4
  modular_interfaces: ^3.0.0
  #logger
  logger: ^2.5.0
  #bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  #添加尺寸.r
  flutter_screenutil: ^5.9.3
  #侧滑
  flutter_slidable: ^3.1.1
  #多语言
  intl: ^0.19.0
  #生成文件
  intl_utils: ^2.0.0
  #加密解密
  crypto: ^3.0.6
  #hex
  convert: ^3.1.2
  #loading
  flutter_easyloading: ^3.0.5
  #toast
  fluttertoast: ^8.2.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  test: ^1.24.3
  coverage: ^1.11.1
  freezed: ^2.3.7


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/themes/
    - assets/config/
    - assets/fonts/

  fonts:
    - family: VWHead_Bold
      fonts:
        - asset: assets/fonts/VWHead-Bold.otf
    - family: VWHead_Regular
      fonts:
        - asset: assets/fonts/VWHead-Regular.otf
    - family: HYQiHei_Bold
      fonts:
        - asset: assets/fonts/HYQiHei-80S.ttf
    - family: HYQiHei_Regular
      fonts:
        - asset: assets/fonts/HYQiHei-60S.ttf


# feature override 开发feature阶段使用
dependency_overrides:
  # 可能的flutter pub get问题
  http: ^1.2.2
  #兼容版本
  win32: ^5.9.0
  archive: ^4.0.1
flutter_intl:
  enabled: true